version: 0.1.{build}
configuration: Release
platform: AnyCpu

before_build:
  - cmd: nuget restore

build:
  verbosity: minimal
  project: CraftSdk/CraftSdk.csproj

after_build:
  - nuget pack CraftSdk/CraftSdk.nuspec -Version %appveyor_build_version%

artifacts:
  - path: LogiCraftSdk.Net*.nupkg
    name: LogiCraftSdk.Net nuget package
    type: NuGetPackage